Autobuild for subdirs

diff --git a/.local/bin/autobuild b/.local/bin/autobuild
--- a/.local/bin/autobuild
+++ b/.local/bin/autobuild
@@ -7,6 +7,7 @@ color=1
 mode="release"
 cppcompiler="clang"
 dryrun=""
+subdir=""
 
 # deploy and result params
 host=autobuild-host
@@ -53,6 +54,10 @@ while [[ $# -gt 0 ]]; do
             ;;
         --host)
             host="$2"
+            shift
+            ;;
+        -s|--subdir)
+            subdir="$2"
             shift
             ;;
         -c|--config)
@@ -153,8 +158,13 @@ elif [ -f main.roc ]; then
     fi
 elif [ -f build.py ]; then
     cwd=$(basename $(pwd))
+    if [ "$subdir" == "" ]; then
+        binary=$cwd
+    else
+        binary=$subdir
+    fi
     if [ "$mode" == "check" ]; then
-        dirs=`jq '.checks | .[]' -r .autobuild.json 2>/dev/null || echo $cwd`
+        dirs=`jq '.checks | .[]' -r .autobuild.json 2>/dev/null || echo $subdir`
         for dir in $dirs; do
             echo "autobuild: Checking directory ${dir}"
             move_msg_files $dir
@@ -164,13 +174,13 @@ elif [ -f build.py ]; then
             move_msg_files $dir
         done
     elif [ "$mode" == "test" ]; then
-        test_targets=`jq '.testTargets | .[]' -r .autobuild.json 2>/dev/null || echo "$cwd"-tests`
+        test_targets=`jq '.testTargets | .[]' -r .autobuild.json 2>/dev/null || echo "${binary}-tests"`
         for target in $test_targets; do
             echo "autobuild: Building test target ${target}"
             python3 build.py $target --compiler $cppcompiler
         done
 
-        tests=`jq '.tests | .[]' -r .autobuild.json 2>/dev/null || echo "test-${cwd}"`
+        tests=`jq '.tests | .[]' -r .autobuild.json 2>/dev/null || echo "test-${binary}"`
         for test in $tests; do
             echo "autobuild: Running test ${test}"
             cross/test-debug-${cppcompiler}/binaries/bin/$test
@@ -186,28 +196,33 @@ elif [ -f build.py ]; then
             echo "Syncing ${entry}"
             $rsync $entry $dst
         done
+        if [ -f .autobuild.json ]; then
+            $rsync .autobuild.json $dst
+        fi
         echo "Starting build on ${host}"
         ssh $host "cd autobuild/${cwd}; autobuild --mode release --compiler ${cppcompiler} --no-clear"
     elif [ "$mode" == "runsim" ]; then
-        ini="${cwd}/sim/config.ini"
-        ini_count=`find . -name "config.ini" | wc -l`
+        ini_count=`find ./${subdir} -name "config.ini" | wc -l`
         if [ "$ini_count" == "1" ]; then
-            ini=`find . -name "config.ini"`
+            ini=`find ./${subdir} -name "config.ini"`
+        else
+            echo "Could not uniquely identify the config.ini"
+            exit -1
         fi
-        run-sim-remote --cwd "autobuild/${cwd}" -b "binaries/bin/${cwd}" -f $ini -c $sim_config -R $sim_R --scale-J $sim_scale_J $dryrun
+        run-sim-remote --cwd "autobuild/${cwd}" -b "binaries/bin/${binary}" -f $ini -c $sim_config -R $sim_R --scale-J $sim_scale_J $dryrun
     elif [ "$mode" == "results" ]; then
         if [ "$host" == "" ]; then
             echo "No host specified for fetching results"
             exit -1
         fi
-        ssh $host "cd autobuild/${cwd}; find results/${sim_config}/ -name '*.sca' -or -name '*.vec' | xargs binaries/bin/opp_scavetool export -o results/${sim_config}/results.json"
+        ssh $host "cd autobuild/${cwd}; find ./${subdir}/results/${sim_config}/ -name '*.sca' -or -name '*.vec' | xargs binaries/bin/opp_scavetool export -o ./${subdir}/results/${sim_config}/results.json"
         mkdir -p results/${sim_config}
-        scp ${host}:autobuild/${cwd}/results/${sim_config}/results.json results/${sim_config}/results.json
+        scp ${host}:autobuild/${cwd}/${subdir}/results/${sim_config}/results.json results/${sim_config}/results.json
     elif [ "$mode" == "open" ]; then
         echo "Unsupported mode ${mode} for build.py projects"
         exit -1
     else
-        targets=`jq '.targets | .[]' -r .autobuild.json 2>/dev/null || echo $cwd`
+        targets=`jq '.targets | .[]' -r .autobuild.json 2>/dev/null || echo $binary`
         for target in $targets; do
             echo "autobuild: Building target ${target}"
             python3 build.py $target --mode $mode --compiler $cppcompiler
